stages:
  - test

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
test:
  stage: test
  script:
    - chmod -R a+rwx gradlew
    - ./gradlew allTests
after_script:
  - echo "End CI"